apiVersion: batch/v1
kind: Job
metadata:
  name: mapreduce-pipeline
  namespace: cc-project
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: hadoop
          image: hadoop-streaming:4.0
          imagePullPolicy: IfNotPresent
          command: ["bash", "/project/scripts/phase2_final.sh"]
          volumeMounts:
            # 1. Mount the Nginx hard drive (contains nginx_access.log)
            - name: nginx-data
              mountPath: /project/data
            
            # 2. Mount the Service hard drive exactly where the script expects it
            - name: service-data
              mountPath: /project/data/service_logs
            
            # 3. Mount the outputs folder back to the Nginx hard drive
            - name: nginx-data
              mountPath: /project/outputs
              subPath: outputs
      volumes:
        - name: nginx-data
          persistentVolumeClaim:
            claimName: nginx-logs-pvc
        - name: service-data
          persistentVolumeClaim:
            claimName: service-logs-pvc